# Generated by Django 4.2.4 on 2023-08-21 06:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Draft", "Draft"),
                            ("Incomplete", "Incomplete"),
                            ("Inactive", "Inactive"),
                            ("Active", "Active"),
                        ],
                        default="Draft",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                ("source_url", models.TextField(blank=True, null=True, verbose_name="url")),
                ("title", models.CharField(blank=True, max_length=255, null=True, verbose_name="title")),
                (
                    "condition",
                    models.CharField(
                        blank=True, choices=[("new_new", "New")], max_length=20, verbose_name="condition"
                    ),
                ),
                ("buy_price", models.IntegerField(blank=True, null=True, verbose_name="buy Price")),
                ("sell_price", models.IntegerField(blank=True, null=True, verbose_name="sell Price")),
                ("quantity", models.IntegerField(blank=True, null=True, verbose_name="quantity")),
                ("description", models.TextField(blank=True, null=True, verbose_name="description")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProductPhoto",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("path", models.ImageField(upload_to="productphoto", verbose_name="image file")),
                (
                    "width",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name="width"),
                ),
                (
                    "height",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name="height"),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="product.product"
                    ),
                ),
            ],
        ),
    ]
