# Generated by Django 4.2.4 on 2023-10-02 09:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="jan",
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name="JAN"),
        ),
    ]
