# Generated by Django 4.2.4 on 2023-10-12 01:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0002_product_jan"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="count_set",
            field=models.IntegerField(blank=True, null=True, verbose_name="count Set"),
        ),
    ]
