# Generated by Django 4.2.4 on 2023-10-18 01:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0003_product_count_set"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="status",
            field=models.CharField(
                choices=[("Draft", "Draft"), ("Inactive", "Inactive"), ("Active", "Active")],
                default="Draft",
                max_length=20,
                verbose_name="status",
            ),
        ),
    ]
