# Generated by Django 4.2.4 on 2023-10-18 02:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0004_alter_product_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductSetting",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("license_key", models.CharField(blank=True, max_length=255, null=True, verbose_name="license Key")),
                (
                    "service_secret",
                    models.CharField(blank=True, max_length=255, null=True, verbose_name="service Secret"),
                ),
                ("shipping_mail_fee", models.IntegerField(blank=True, null=True, verbose_name="email Shipping Fee")),
                ("shipping_60_fee", models.IntegerField(blank=True, null=True, verbose_name="60 Shipping Fee")),
                ("shipping_80_fee", models.IntegerField(blank=True, null=True, verbose_name="80 Shipping Fee")),
                ("shipping_100_fee", models.IntegerField(blank=True, null=True, verbose_name="100 Shipping Fee")),
                ("shipping_120_fee", models.IntegerField(blank=True, null=True, verbose_name="120 Shipping Fee")),
                (
                    "scraping_update_amazon_from",
                    models.IntegerField(blank=True, null=True, verbose_name="upadating Amazon Time"),
                ),
                (
                    "scraping_update_tajimaya_from",
                    models.IntegerField(blank=True, null=True, verbose_name="updating Tajimaya Time"),
                ),
                (
                    "scraping_update_oroshi_from",
                    models.IntegerField(blank=True, null=True, verbose_name="updating Oroshi Time"),
                ),
                (
                    "rakuten_fee",
                    models.IntegerField(
                        choices=[(0, "Zero"), (8, "Eight"), (10, "Ten")], default=10, verbose_name="rakuten Fee"
                    ),
                ),
            ],
        ),
    ]
