# Generated by Django 4.2.4 on 2023-10-18 02:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("product", "0005_productsetting"),
    ]

    operations = [
        migrations.AddField(
            model_name="productsetting",
            name="created_by",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="productsetting",
            name="rakuten_fee",
            field=models.IntegerField(
                choices=[(0, "Zero"), (8, "Eight"), (10, "Ten")], default=10, verbose_name="rakuten Fee"
            ),
        ),
    ]
