# Generated by Django 4.2.4 on 2023-10-30 04:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0007_product_manage_number_product_point_product_profit_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="shipping_method",
            field=models.CharField(
                choices=[
                    ("shipping_mail", "Shippingmail"),
                    ("shipping_60", "Shipping60"),
                    ("shipping_80", "Shipping80"),
                    ("shipping_100", "Shipping100"),
                    ("shipping_120", "Shipping120"),
                ],
                default="shipping_mail",
                verbose_name="shipping Method",
            ),
        ),
        migrations.AlterField(
            model_name="productsetting",
            name="rakuten_fee",
            field=models.IntegerField(
                choices=[(0, "Zero"), (8, "Eight"), (10, "Ten")], default=10, verbose_name="rakuten Fee"
            ),
        ),
    ]
