# Generated by Django 4.2.4 on 2023-11-07 05:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0008_product_shipping_method_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productsetting",
            name="rakuten_fee",
            field=models.IntegerField(
                choices=[(0, "Zero"), (8, "Eight"), (10, "Ten")], default=10, verbose_name="rakuten Fee"
            ),
        ),
    ]
