# Generated by Django 4.2.4 on 2023-09-28 13:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="license_key",
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="license Key"),
        ),
        migrations.AddField(
            model_name="user",
            name="service_secret",
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="service Secret"),
        ),
    ]
