# Generated by Django 4.2.4 on 2023-10-18 02:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_user_license_key_user_service_secret"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="license_key",
        ),
        migrations.RemoveField(
            model_name="user",
            name="service_secret",
        ),
    ]
